### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by aogaili** [henrykuzmick/react-skeleton-loader#3]
I get an error that window is not defined when attempting to SSR the component, does this loader support SSR?

**Comment by aogaili** [comment]
I think it has to do with source map support.

**Comment by tchalvak** [comment]
I have a similar error happening whenever I go to build my static app assets! The build context has no window and does not like something about the distributed source that is checking it.  I’d love to be able to use this library, it makes an app much more professional, are you open to a pull request in this area?

**Comment by henrykuzmick** [comment]
Hey, sorry for the very late response, PRs are definitely welcome
